version: "3"

services:
  hot-deals:
    container_name: hot-deals-bot
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    working_dir: /app
    volumes:
      - .:/app

  hot-deals-prod:
    container_name: hot-deals-bot-prod
    build:
      context: .
      target: prod
